name: Build Tiny

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: gcc tiny.c -pthread -o tiny_linux.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiny_linux.bin
          path: tiny_linux.bin

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: gcc tiny.c -pthread -o tiny_macos.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiny_macos.bin
          path: tiny_macos.bin

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MinGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc

      - name: Build
        run: gcc tiny.c -o tiny_windows.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiny_windows.exe
          path: tiny_windows.exe
